# Generated by Django 5.1.2 on 2024-10-26 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_jobseekermodel_recruitermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('num_of_openings', models.PositiveIntegerField(null=True)),
                ('category', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], max_length=50)),
                ('description', models.TextField(max_length=500, null=True)),
                ('skills', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
