# Generated by Django 5.1.2 on 2024-10-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_jobmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='company_logo',
            field=models.ImageField(null=True, upload_to='Media/Company_Logo'),
        ),
    ]
