# Generated by Django 5.1.2 on 2024-10-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_jobapplymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekermodel',
            name='skills',
            field=models.CharField(choices=[('programming', 'Programming'), ('networking', 'Networking'), ('hardware', 'Hardware')], max_length=100, null=True),
        ),
    ]
