# Generated by Django 5.1.2 on 2024-10-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_jobseekermodel_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='skills',
            field=models.CharField(choices=[('programming', 'Programming'), ('networking', 'Networking'), ('hardware', 'Hardware')], max_length=50, null=True),
        ),
    ]
